### ISSUE TITLE
Seek the video!

### ISSUE THREAD

**Issue by MozzieMD** [bbougot/Popcorn#1]
Did you tried to make seek possible? i mean when you seek it will start downloading from there!?

**Comment by bbougot** [comment]
It's work in progress! I think this functionnality will come out next week

**Comment by MozzieMD** [comment]
Nice, one more thing, i'm new to c# and can't really get all your code, but i want to make same thing just from russian tracker, could you make visual studio solution with simple libtorrent wrapper and xZune.Vlc without the design and api? i want to get how it works!

**Comment by bbougot** [comment]
Well, this is not that complex, what you need is a project which include the Ragnar library (https://github.com/libragnar/ragnar). It's a simple wrapper of libtorrent-rasterbar. Then, you have to create an asynchronous method : 
```csharp
using(var session = new Session())
{
    // Make the session listen on a port in the range
    // 6881-6889
    session.ListenOn(6881, 6889);

    // Create the AddTorrentParams with info about the torrent
    // we'd like to add.
    var addParams = new AddTorrentParams
    {
        SavePath = "C:\\Downloads",
        Url = "<url to a torrent file>",
        Trackers.Add("YOUR TRACKER HERE")
    };

    // Add a torrent to the session and get a `TorrentHandle`
    // in return.
    var handle = session.AddTorrent(addParams);

    while(true)
    {
        // Get a `TorrentStatus` instance from the handle.
        var status = handle.QueryStatus();

        // If we are seeding, our job here is done.
        if(status.IsSeeding)
        {
            break;
        }

        // Print our progress and sleep for a bit. Cancel task with the cancellation token ct at any time.
        Console.WriteLine("{0}% downloaded", status.Progress * 100);
        await Task.Delay(1000, ct);
    }
}
```

**Comment by MozzieMD** [comment]
Thanks, so you download the file, not some kind of buffer?

**Comment by bbougot** [comment]
Sorry, I forgot to add handle.SequentialDownload = true. Indeed, the download has to be sequential so that the play can read seamlessly the file

**Comment by MozzieMD** [comment]
yeah i did that in an old fashion way without view models ) just mainwindow and it works if i wait at least 5% before starting the video, so i don't get silver artifacts, the only thing is seeking ) waiting to see how you will do it !

**Comment by MozzieMD** [comment]
one more, how do you dispose the vlcplayer, cause i do await for PlayerStopAsync and do Dispose() method but i get an exception sometimes when i close the window, it tries to setValue of current video position after it stops!

**Comment by bbougot** [comment]
You're doing it the right way. You should ask the author of xZune because it's kinda a bug. A workaround for you would be pausing the player. Before await PlayerStopAsync, just do : player.PauseOrResume();

**Comment by MozzieMD** [comment]
Good idea, i will try!

**Comment by MozzieMD** [comment]
Didn't help, i will ask xZune author, and do you have any ideas how to get rid of silver screen and rendering problems, i think this is because that piece is still not downloaded right?

**Comment by bbougot** [comment]
Problems related to missing frames (due to an incomplete download) would result in artefacts, not in a completely silver screen I guess. Maybe the aspect ratio isn't set correctly or something...

**Comment by MozzieMD** [comment]
well your player have the same problem, any ideas to fix that?? i think it's a ragnar sequential download  problem!

**Comment by MozzieMD** [comment]
Do you know how to do this:
Change the first few piece priority to 7 and 0 for the rest. After those pieces are downloaded, I change the rest back to priority 1.

Can't find a method to change piece priority!

**Comment by MozzieMD** [comment]
Ok man, it seems I found what is causing silver frame(screen), it's the hard drive, the problem is that VLC has some problems reading a file that's used by other program, in our case, libtorrent, so by using this option when initializing VLC `--file-caching=1000`, for a longer Cache by VLC, this seems to solve the problem, anyway needs more testing!
