### ISSUE TITLE
Add Linux Support

### ISSUE THREAD

**Issue by applesea2** [bbougot/Popcorn#100]
I have several of my machines running Linux. Maybe it can be ported over?

**Comment by bbougot** [comment]
It would be great but the framework used (WPF) does not let making a port to other platforms easily. It would require a huge amount of work.

**Comment by Scellow** [comment]
If you port UI to Xamarin.Forms then you'll be able to target everything 

https://github.com/xamarin/Xamarin.Forms/pull/1334

https://github.com/xamarin/Xamarin.Forms/pull/1174

It is not yet officially released and porting UI code will be long task, but i think it worth it, you'll also be able to port to mobile, wich will give you opportunity to ad Ads for revenue :)
