### ISSUE TITLE
random video freezes/glitches

### ISSUE THREAD

**Issue by beppe9000** [bbougot/Popcorn#113]
I don't know if it is the video file or the media player, but while playing a (fully buffered!) movie in Popcorn it showed random visual freeze/glitches (about twice per minute). If I open the video file with my preferred media player (MPC) playback is flawless.

**Comment by bbougot** [comment]
I confirm the issue, I've encountered several times. I will fix it soon.

**Comment by beppe9000** [comment]
maybe some internal buffering problem?

**Comment by bbougot** [comment]
I changed buffering strategy along with version 3.2.0
Please tell me if antyhing changed for good/bad

**Comment by beppe9000** [comment]
I still experience this. A couple of seconds of freezing, then glitches (showing video artifacts) and continues.
