### ISSUE TITLE
Add a 'How to compile' to the readme

### ISSUE THREAD

**Issue by beppe9000** [bbougot/Popcorn#114]
I tried loading the sources in VS2017 but it wasn't able to compile due to a lot of errors. Did I forgot to do something like setup dependencies? Wasn't that automatic for nuget packages?

**Comment by bbougot** [comment]
Try to rebuild Popcorn project, sometimes VS fail to build at first because of some missing dependencies. The second try should be fine

**Comment by beppe9000** [comment]
I figured it was a low space issue preventing VS from refreshing the nuggets...

**Comment by beppe9000** [comment]
I solved the space issue but i get a couple of errors about "netstandard" not existing.
