### ISSUE TITLE
Add an option to disable the program automatically opening magnet links

### ISSUE THREAD

**Issue by Constant-ine** [bbougot/Popcorn#115]
I was looking for a PopcornTime alternative and installed this, looked fine, however after I closed it, I went into a torrent site and clicked on the magnet link, my torrent client didn't open however, Popcorn did, had to delete it off my computer and set my torrent client to handle magnet links again, this is obviously very annoying, also why not create an installer(and uninstaller) for this software so it doesn't constantly run in the background in our appdata folder (which makes it look sketchy) Thanks.

**Comment by beppe9000** [comment]
In my opinion it should not open magnets by default and offer to register the global magnet protocol handler in the settings panel, if this is really necessary (I suppose people don't normally expect to watch their Linux distributions).
