### ISSUE TITLE
About running in the background

### ISSUE THREAD

**Issue by beppe9000** [bbougot/Popcorn#129]
Once I close the Popcorn window I would naturally expect that all and every Popcorn-related processes stop running. Does Popcorn keep running in the background for buffering reasons or just for ease of access through the tray icon?

Anyways I think that this behavior too is one of those things that should be disabled by default.

**Comment by bbougot** [comment]
This feature will be used when https://github.com/bbougot/Popcorn/issues/119 will be implemented. I released it too soon.
