### ISSUE TITLE
Subtitles isn't appearing on chromecast mode.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [bbougot/Popcorn#135]
When watching a video with subtitles, if I decide to stream it via chromecast, the subtitles stay on the app and aren't casted on the chromecast stream.

**Comment by bbougot** [comment]
I'm aware of this issue, tracked here : https://github.com/kakone/GoogleCast/issues/8

**Comment by Tovarichtch** [comment]
Any update on this bug ?

**Comment by PoorPocketsMcNewHold** [comment]
@Tovarichtch This bug depends on entirely an issue with [kakone/GoogleCast#8](https://github.com/kakone/GoogleCast/issues/8)
Since it seems that the GoogleCast repo hasn't received any new commits since the 18 September, I'm afraid that they're still no update on this bug.

**Comment by bbougot** [comment]
Yup, @PoorPocketsMcNewHold is right. I will try to fork GoogleCast and fix it on my own.

**Comment by kakone** [comment]
I added the subtitles support in [GoogleCast 1.4](https://www.nuget.org/packages/GoogleCast/1.4.0).

**Comment by bbougot** [comment]
Fixed in a4a1d42926f086102983cd719d3b14cc5e6452a1

**Comment by kakone** [comment]
I also added the TextTrackStyle property in [GoogleCast 1.5](https://www.nuget.org/packages/GoogleCast/1.5.0) :
```csharp
media.TextTrackStyle = new TextTrackStyle()
{
    BackgroundColor = Color.Transparent,
    EdgeColor = Color.Black,
    EdgeType = TextTrackEdgeType.DropShadow
};
```

**Comment by bbougot** [comment]
Great! Thank you I will support it in the following releases of Popcorn 👍
