### ISSUE TITLE
Latest episodes are not available.

### ISSUE THREAD

**Issue by Weeeishy** [bbougot/Popcorn#139]
Hello,

I'm sorry, but I'm not quite sure if this is an issue or intentional, but I've noticed that some tv shows like The Walking Dead and The Flash are not updating regularly and their episodes are not available through this version of Popcorn. I've checked the original Popcorn and they are available there. These episodes were aired some time ago, like we are talking few days ago. Again, if this is not an issue, then please feel free to close the issue.

Thank you for your time.

**Comment by Malavos** [comment]
I have noted that it takes some hours to appear once they are online, I don't know exactly why (haven't checked that part of the source yet).

@bbougot  could you clarify that?

**Comment by bbougot** [comment]
Shows and movies are updated every 24 hours from the official Popcorn Time API. Hence, there is a delay between the catalog which is expected. However, I can update the interval to make it shorter (like every 4 hours).

However, regarding this issue, there was actually a problem with the exporter itself which was preventing the shows from being updated for at least 3 days. It was fixed and now you should be able to get the same catalog between the two apps.

**Comment by Weeeishy** [comment]
Makes sense. Yeah, changing it to 4 hours will definitely make things better.


Thank you for your clarification and the exporter fix.

**Comment by bbougot** [comment]
Exporter scheduling has been changed to 4 hours, closing issue.
