### ISSUE TITLE
Add torrent providers

### ISSUE THREAD

**Issue by ghost** [bbougot/Popcorn#143]
I know it could be complicated and much more time consuming, there's a lot of recent stuff on YTS but there's not enough episode on EZTV and a lot of them aren't in hd and just soundtracking the tv. here's a list of what you could add (they're all used on DuckieTV) : ThePirateBay,1337X,ETTV,IDOPE,KAT,LimeTorrent,NYAA,RARBG,ShowRSS,SkyTorrents,TorrentDownloads,TorrentZ2,ZOOQLE

**Comment by bbougot** [comment]
Would be great but it requires indeed a huge amount of work, that I cannot handle at this time. I let the issue open, but can't estimate any ETA.

**Comment by invu** [comment]
Perhaps create an export console app to do all the work for you, then simply write to where you store your current torrents.

**Comment by bbougot** [comment]
Problem is, regarding all of the remaining and working torrent providers, all of them require an authentication and mainly of these (YggTorrent, T411) ask for a positive ratio of download/upload I can't trust. It is nearly unfeasible pratically and would required a huge amount of work. I will keep the current provider for Popcorn but I will not be able to add others.

**Comment by Nallat** [comment]
@bbougot Almost no torrent providers on this list need identification, and YggTorrent and T411 are not in the list.
