### ISSUE TITLE
Not working on Chromecast

### ISSUE THREAD

**Issue by Tovarichtch** [bbougot/Popcorn#148]
I can't get chromecast to work with Popcorn 3.4.3.

I start up the movie or TV show from the application, then I click to cast on my chromecast but it keeps loading and ... nothing happens. I took a movie for example. It get stucks either here (first pic) after a long loading (second pic) : 

![23760421_842099435952036_1452116763_o](https://user-images.githubusercontent.com/32983607/32986545-719d3770-cca2-11e7-85e3-2d6416c52793.jpg)

![23732429_842099422618704_1018422346_o](https://user-images.githubusercontent.com/32983607/32986549-7aa38b3a-cca2-11e7-91c0-affda47ee682.jpg)

Nothing happens afterward.

This problem happens on both first and second chromecast generation devices.

**Comment by plucian22** [comment]
how did this get solved ?

**Comment by Tovarichtch** [comment]
I did some tests. Chromecast is working for movies but not for shows.
