### ISSUE TITLE
Subtitles not shown on video?

### ISSUE THREAD

**Issue by CodeSwine** [bbougot/Popcorn#149]
![step 1](https://images2.imgbox.com/cf/1e/1g9TmFyi_o.png)
![step 2](https://images2.imgbox.com/87/33/7Ab8UiK5_o.png)
![step 3 no subtitles](https://images2.imgbox.com/de/97/ZnCRSBnC_o.png)

There is no error log anywhere, subtitles are downloaded into the subtitles folder in %temp%/Popcorn. Tried changing languages but it still doesn't work. I've set my default language in the settings but it doesn't seem to pick it up once the movie actually plays (i manually selected subtitles in the third screenshot).

Please update me if I need to delete the images.

**Comment by bbougot** [comment]
Issue should be fixed along with the release v3.4.8
Could you try again and tell me if anything changed?

**Comment by Malavos** [comment]
@CodeSwine  if anything, a full removal and a new installation should fix everything with 3.4.

**Comment by CodeSwine** [comment]
Yup, everything is working fine now. thanks!
