### ISSUE TITLE
Covers not loading & Can't watch movies.

### ISSUE THREAD

**Issue by Weeeishy** [bbougot/Popcorn#150]
Hi,

I've downloaded the latest release, and apparently the covers are not loading. Also, when I hit the watch button, the buffering page shows up for few seconds and then redirects me back to the movie page. Some TV shows covers are loading fine and some not, although I can watch them without any issues.

https://i.gyazo.com/065ffc1f094ec73582f4349d87644fad.png

https://i.gyazo.com/3a27eaa8bf6311800f3b85daec18ef51.mp4

Thanks

**Comment by bbougot** [comment]
Sorry for this issue, I am rebuilding the entire database to improve its performances. It will take up to 5 hours and everything will go back to normal after.

**Comment by Weeeishy** [comment]
Thanks for the headsup and the fast response.

Goodluck!
