### ISSUE TITLE
Add a default image for actors instead of a black image

### ISSUE THREAD

**Issue by Nallat** [bbougot/Popcorn#152]
I recreated this issue because some of the actors' images are still black.
![acteur](https://user-images.githubusercontent.com/33554398/33221140-b6f86c72-d14d-11e7-9e30-5a7e0cf4e256.png)

**Comment by bbougot** [comment]
The issue is related to #150

**Comment by Nallat** [comment]
@bbougot Oh right, I hadn't seen sorry I polluted the issue tracker
