### ISSUE TITLE
Small UI Enhancement

### ISSUE THREAD

**Issue by Constant-ine** [bbougot/Popcorn#153]
![UIDemo](https://i.imgur.com/FDNzl0e.jpg)

**Comment by invu** [comment]
This is normally the default for fly-in menus, so I'm sure it was the devs choice.

**Comment by Constant-ine** [comment]
>  @invu > _This is normally the default for fly-in menus, so I'm sure it was the devs choice._ 

I see, it just feels smoother to me and makes the experience a tad bit faster since you don't have to move the mouse up and aim at the arrow button, I know it's something very minuscule but still. Oh well let's see what he thinks 😄

**Comment by bbougot** [comment]
Actually it's a nice idea, by default fly-out are pinned but the ability to dismiss it by mouse is great I think.
