### ISSUE TITLE
Movies not loading

### ISSUE THREAD

**Issue by GeorgeSkyway** [bbougot/Popcorn#16]
Movies are not loading i'm getting critical error.

windows 10 64 bit

http://imgur.com/a/ZDB7L

**Comment by bbougot** [comment]
Could you check the log stored in C:/Users/[USERNAME]/AppData/Local/Temp/Popcorn/Logs ?
Please past them in a gist (Fatal and Error are the most appropriate).

**Comment by RonnyDT** [comment]
I have the same issue, the log is in dutch though.

Roughly translates to "Can't find file or assembly Itnet.dll or can't load one of the dependencies. Can't find given module. Filename: Itnet.dll". 

[Fatal-2017-03-17.txt](https://github.com/bbougot/Popcorn/files/850112/Fatal-2017-03-17.txt)

**Comment by bbougot** [comment]
App was missing Visual C++ 15 Redist. 
Added libs to the project.
