### ISSUE TITLE
[Enhancement] Hide already seen movies

### ISSUE THREAD

**Issue by Nallat** [bbougot/Popcorn#161]

**Comment by beppe9000** [comment]
duplicate #110

**Comment by Nallat** [comment]
@beppe9000 @bbougot Okay, I'm closing the issue

**Comment by Getexis** [comment]
Has this improvement been implemented or has it been canceled?
Because in my version 3.6 still continues to show the movies already watched.

**Comment by bbougot** [comment]
Issue #110 is still opened. It is not clear I will implement this functionnality. I will dig into this in the future.
