### ISSUE TITLE
[Enhancement] The title and synopsis of the films are in English and then in the chosen language.

### ISSUE THREAD

**Issue by ghost** [bbougot/Popcorn#162]
It would be better if the titles and synospis of the films would be in the chosen language directly
![2e2be54a-08e4-4ee1-8e6f-7664c8c77b41](https://user-images.githubusercontent.com/33554398/33445911-b13236b4-d5fe-11e7-82d6-2f3a416d73b2.GIF)

**Comment by bbougot** [comment]
Actually, the translated movie infos are retrieved from an other provider (TMDb) and it requires some time to get fetched. This is why there is a delay between original title and the translated one. But I find it better than displaying a spinner loader and wait for the fetch to be finished.
