### ISSUE TITLE
Close program directly when in "about" or "help" pages

### ISSUE THREAD

**Issue by nachopique** [bbougot/Popcorn#166]
When you are in the help or about pages you can not close the program by clicking right buton of the mouse/close in the task bar. Also, you can't close it direcly with te X in the upper right corner when in those pages. 
I'm asking to add both features presented above.
Sorry for my bad english.

**Comment by bbougot** [comment]
I will add these features to the board.

**Comment by bbougot** [comment]
Refactored UX, issue solved.
