### ISSUE TITLE
Unnecessarily high prebuffering 

### ISSUE THREAD

**Issue by applesea2** [bbougot/Popcorn#167]
I noticed when trying to watch any movie or show that even though I get excellent speeds, I find that Popcorn Time downloads a much larger chunk of the movie/show than is required to play consistently. For example, most movies seem to download a good 20 minutes just on the prebuffer and I find that unnecessary for most stable internet connections.The original popcorn time only downloads a few minutes and I never have to wait long for it to prebuffer or have any buffering in scene. Change the percentage required to prebuffer or provide some sort of setting

**Comment by Constant-ine** [comment]
Already been reported, https://github.com/bbougot/Popcorn/issues/164

**Comment by beppe9000** [comment]
should be implemented #103

**Comment by Nallat** [comment]
@applesea2 I've already created a similar issue, close this one please.
