### ISSUE TITLE
Subtitle and magnet

### ISSUE THREAD

**Issue by harix786** [bbougot/Popcorn#168]
First of all i appreciate your great work 🥇 👍 
1. Can we add magnet link or torrent file link in the detail section of movies and show ?
2. When we click on subtitle option while playing the movie the cancel option did not work and stucks on that screen untill we close the application
Can you guide me about this

**Comment by bbougot** [comment]
Thank you, much appreciated 👍 

1. You can copy and paste your link into the UI of Popcorn, it will download and play the media from the torrent.magnet
2. Look like an issue, I will investigate this

**Comment by harix786** [comment]
1.How to change a folder name which creates in Appdata/local/Temp/popcorn when application runs
2.When i changed the assembly name all the titles and labels looks like this ---> Key:PopularTitleTab / Key:SettingsMenuTitle <---  
Can You help me how to fix these

**Comment by harix786** [comment]
2nd Issue is almost resolved . I have changed the "Assembly Name" and all is working great except media player when we click on watch trailer or download any movie/show the media player did not shows its template, icons or any thing

About and help section looks like this 

![screenshot 4](https://user-images.githubusercontent.com/24369463/34318587-9ed9c15c-e7ed-11e7-95e0-9d61d30b330b.png)

Now the main screen is looks like good 
Step 1:
![0](https://user-images.githubusercontent.com/24369463/34318555-f9069516-e7ec-11e7-8183-6ddbc0a11d69.png)
Now click on the trailer 
Step2:
![1](https://user-images.githubusercontent.com/24369463/34318547-e07c7948-e7ec-11e7-939a-639feb2fde76.jpg)
Step3:
![2](https://user-images.githubusercontent.com/24369463/34318559-104fdf66-e7ed-11e7-9bbd-5870d725fdf7.png)
Now the close, minimize menu is disappeared and also the task bar when the application is in fullscreen mode 
Step4:
![3](https://user-images.githubusercontent.com/24369463/34318561-15cf6894-e7ed-11e7-9ece-1350b7ef5acf.jpg)
Step5:
![4](https://user-images.githubusercontent.com/24369463/34318562-19d7dcfa-e7ed-11e7-8fcd-15d3cefdca84.jpg)
Step6:
![5](https://user-images.githubusercontent.com/24369463/34318565-2c2ab242-e7ed-11e7-9f02-fd2168c2f3bd.jpg)
Step7:
![6](https://user-images.githubusercontent.com/24369463/34318569-39b3393e-e7ed-11e7-8656-bc1daaf0508f.jpg)
By clicking back button again it looks like good
Step8:
![7](https://user-images.githubusercontent.com/24369463/34318572-433da480-e7ed-11e7-948e-592d3a011bf1.png)

**Comment by harix786** [comment]
What i figure it out all the problem starts when i changed the "assembly name"
is there any way to change the assembly name to other and it should not effect on the app?
