### ISSUE TITLE
Subtitles bug

### ISSUE THREAD

**Issue by TheProxyRE** [bbougot/Popcorn#170]
I came across bug on move "Fight club".
In video player when i select subtitle cancel button doesn't function and i cant close dialog, or when i select subtitle before playing video it gets stuck at buffering screen

**Comment by bbougot** [comment]
Which version of Popcorn are you using? You will get it in the settings panel.

**Comment by TheProxyRE** [comment]
![slika](https://user-images.githubusercontent.com/12687236/34457747-e5931a44-edba-11e7-8171-918203a3488f.png)

**Comment by bbougot** [comment]
The update process can take a while (up to 1 minute). 
The issue you are mentioning should be fixed from release 3.4.8

**Comment by bbougot** [comment]
Any update?

**Comment by bbougot** [comment]
No news about this issue, closing.
