### ISSUE TITLE
[Enhancement] Add French and Spanish torrent providers

### ISSUE THREAD

**Issue by ghost** [bbougot/Popcorn#171]
To change the audio language .
For French-language yggtorrent.com , torrent9.bz , oxtorrent.com , cpabien.cx
For spanish I don't know.

**Comment by harisnaeem** [comment]
Can u add bollywood movies torrent provider also ? bcz other popcorn apps provide all bollywood and hollywood movies

**Comment by Nallat** [comment]
@ghost @bbougot  This list is obselete, here is a list of french torrent providers : 

Cpasbien : https://www.cpabien.cm Crawler : https://github.com/romainfrancois/cpasbien 

YggTorrent : https://yggtorrent.com Crawler : https://github.com/pitzzae/yggtorrent, https://goo.gl/ajVx6D 

Torrent9 : https://www.torrent9.cx    Crawler : https://goo.gl/ajVx6D 

GkTorrent : https://www.gktorrent.net 

T411 : https://torrent411.xyz Crawler : https://github.com/thibauts/t411

**Comment by bbougot** [comment]
Problem is, regarding all of the remaining and working torrent providers, all of them require an authentication and mainly of these (YggTorrent, T411) ask for a positive ratio of download/upload I can't trust. It is nearly unfeasible pratically and would required a huge amount of work. I will keep the current provider for Popcorn but I will not be able to add others.
