### ISSUE TITLE
希望加入中文和可更改安装路径

### ISSUE THREAD

**Issue by David318** [bbougot/Popcorn#178]
安装路径希望可以更改，个人不喜欢把软件都装到系统盘，系统盘也比较小。

英文也不影响使用，如果可以的话希望能够加入中文

**Comment by Constant-ine** [comment]
I believe our friend is asking for the installer to be able to have a custom installation path.

**Comment by bbougot** [comment]
The installer is made for being stealth, without warning and so on (for those who would like to ask, it is Squirrel.Windows (https://github.com/Squirrel/Squirrel.Windows). I chose it to be fast with no prompt, so basically I will not be able to show an option to change the installation path.
