### ISSUE TITLE
[Issue] Strange encoding in caption (PT-BR)

### ISSUE THREAD

**Issue by Getexis** [bbougot/Popcorn#182]
![2018-02-09_21-29-39](https://user-images.githubusercontent.com/2664981/36210277-2a119fa4-1185-11e8-9f32-1062cb1f6326.png)

All the characters that have accentuation, behave with a strange encoding.

**Comment by bbougot** [comment]
Fixed in a4a1d42926f086102983cd719d3b14cc5e6452a1
