### ISSUE TITLE
Not supported, French characters in the subtitles.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [bbougot/Popcorn#183]
Missing the "éÉàèùÀÈÙâêîôûÂÊÎÔÛëïËÏçÇ" characters.
Showed in those two examples, the é.
https://horobox.co.uk/u/f0Y5V3.jpg
https://horobox.co.uk/u/nfqwpb.jpg

**Comment by bbougot** [comment]
Fixed in a4a1d42926f086102983cd719d3b14cc5e6452a1
