### ISSUE TITLE
play button (triangle), superimposed on the poster center does not start video

### ISSUE THREAD

**Issue by spartan77777** [bbougot/Popcorn#187]
play button should mean play, instead, it acts like the rest of the poster surface and just takes you to the detail page instead of triggering the "watch" action.

**Comment by bbougot** [comment]
It is debatable, but I think it is not a showstopper for the UI/UX. Clicking the cover should, in all of the cases, lead to the details in order to choose the download options. Maybe the play logo is clumsy but... waiting for an other logo idea, I will let it unchanged.
