### ISSUE TITLE
Torrent like working structure should inlude a copyright disclaimer/notice

### ISSUE THREAD

**Issue by spartan77777** [bbougot/Popcorn#188]
Popcorn appears to be utilizing a form of torrent protocol.  If the popcorn client in any part of it's functionality performing any upload for other peers, then there are definite copyright violation issues in certain countries at a minimum.  Even if it strictly downloads it may still be illegal.  Therefore, a notification popup at startup in necessary, warning of such risk/exposure.

**Comment by PoorPocketsMcNewHold** [comment]
The App is only distribued trought this repository, In which include a License who does warm the user about it.

This project and the distribution of this project is not illegal, nor does it violate any DMCA laws. The use of this project, however, may be illegal in your area. Check your local laws and regulations regarding the use of torrents to watch potentially copyrighted content. The maintainers of this project do not condone the use of this project for anything illegal, in any state, region, country, or planet. Please use at your own risk.

It would still be a great addition to add it again, in case of the user who didn't read everything.

**Comment by bbougot** [comment]
There is already, as @PoorPocketsMcNewHold  said, several warning regarding legal concerns, including the app and this Github repo.
