### ISSUE TITLE
Bollywood movie category on PopcornTime

### ISSUE THREAD

**Issue by TinyOutsider** [bbougot/Popcorn#191]
What is the possibility of adding Bollywood (Hindi) movie category? Since all movies are coming from torrents, and there are hundreds of Bollywood movies made each year. There is definitely a lot of demand for it.
Is there any way we can help with it?
Thanks.

**Comment by bbougot** [comment]
I will not add any other provider, this a much complex task to find a great torrent provider which is free/limitless/working/...
