### ISSUE TITLE
Subtitle Sync

### ISSUE THREAD

**Issue by darkdex52** [bbougot/Popcorn#192]
There needs to be a way to sync subtitles in player. I tried F1/F2 and G/H and even shift+G/H and nothing works. If there is a way to do it, then it needs a place to be explained how.

**Comment by Weeeishy** [comment]
That would be really nice feature to have just like the original Popcorn time. A lot of subtitles are just desynced so I'm kinda forced to use a custom subtitle.

**Comment by bbougot** [comment]
Actually it is already available using G and H keys. You should be able to see a caption while playing the video with the current delay.
