### ISSUE TITLE
about content

### ISSUE THREAD

**Issue by 1470391328** [bbougot/Popcorn#193]
can you add anime and tv show torrent? Besides , can you provide different torrents for every one movie to choose? Can you add torrent search engine and torrrent play feature?  can you provide more chinese sub from  china subtitle site ？thanks your work！！！ come on！！！ i  am from china!!!

**Comment by bbougot** [comment]
There is no good provider for anime (and I mean, good provider with well documented API), so it will be complicated to add to Popcorn.
TV Show is already available in the app.
Torrent search engine is not a feature I would like to app, this app is conceived with the aim to provide a great interface to watch any movie/TV show and is not a torrent search platform.
Subtitles are provided entirely by OpenSubtitles, hence it is not possible to changed anything to this.
