### ISSUE TITLE
Buffering indefinitely.

### ISSUE THREAD

**Issue by Weeeishy** [bbougot/Popcorn#197]
Hello,

I'm having that weird bug where the Buffering sign stays forever if I reset the show back to 00:00, even though the download speed is fast enough . The workaround is to just wait and drag the timer back to 00:00 again. I'm not sure if it's just happening to me or it is an actual bug.

Thank you.

**Comment by bbougot** [comment]
There is issues regarding buffering, I will fix them ASAP.

**Comment by RDeluxe** [comment]
I'm encountering the same issues

**Comment by Tovarichtch** [comment]
Same here. It wasn't like that before.

**Comment by bbougot** [comment]
Fixed in release 5.0.0.
