### ISSUE TITLE
Subtitles not working

### ISSUE THREAD

**Issue by Shatayuz** [bbougot/Popcorn#206]
**Describe the bug**
Subtitles not working

**To Reproduce**
Only option "None" in both Settings and when selecting any movie.

**Expected behavior**
Get any option besides "None"

**Screenshots**
None

**Desktop**
 - OS: Windows 10 Pro N (1803)
 - OS Version: 17134.81

**Additional context**
All Windows updates done. Reinstalled Popcorn and updated to new version. Checked Windows firewall, no issue there. Tried waiting a few minutes to make sure it wasn't just slow loading, no difference in either places. I tried searching for anything subtitle related on this org, but couldn't find anything.
Edit: it didn't work in any version of Popcorn (of the two I have had) for me.

**Comment by bbougot** [comment]
Are you still having this issue? I've checked multiple times on different environments and I don't reproduce it.

**Comment by Shatayuz** [comment]
Will yeah it's been like this since I first installed it to be honest. Not only this, but watching anything makes it so that if I press spacebar when not focusing on Popcorn, still pauses the video. Any shortcut actually does its intended purpose on Popcorn, it's truly annoying
