### ISSUE TITLE
47 Errors when building Popcorn.sln on Visual Studio

### ISSUE THREAD

**Issue by Ao7378** [bbougot/Popcorn#214]
When i ran Popcorn.sln and attempted to build it on visual studio enterprise 2017 i got 47 errors i cant write them all down but is there a fix for the 47 errors  did you use the mac version of visual studio or windows version

**Comment by bbougot** [comment]
Popcorn will not build under Mac OS environment.
Pretty sure it is a NuGet dependency retrieving failure. Under Windows, try to clean and rebuild the solution.

**Comment by Goe23** [comment]
@bbougot since there is a wontfix label, maybe you do want close this issue?
