### ISSUE TITLE
subtitle delay doesn't work

### ISSUE THREAD

**Issue by zXemn4s** [bbougot/Popcorn#217]
**To Reproduce**
1. Open any movie or tv show
2. Press G or H to change subs delay

**Expected behavior**
It should delay subs to sync them with movies, but it doesn't

**Desktop:**
 - OS: Windows 10
 - Popcorn Version 5.0.1

**Comment by bbougot** [comment]
Closing, this issue is already tracked here: https://github.com/bbougot/Popcorn/issues/208
