### ISSUE TITLE
How to download? The installer link on the front page is broken

### ISSUE THREAD

**Issue by JellyGummy** [bbougot/Popcorn#229]
Hi, the installer link on the front page is broken how do I run this? I downloaded and extracted the zip file and I still dont get how to open it sorry and thank you

**Comment by bbougot** [comment]
Should be fixed now.

**Comment by bbougot** [comment]
There's no npm command, it's a full .NET/WPF application, hence you have to download VIsual Studio (2017 or 2019), open Popcorn.sln and Hit F5 to run/debug or set to "Release" mode and build the entire solution. It will produce the PopcornInstaller in Popcorn/Popcorn/Releases folder.
