### ISSUE TITLE
Description View exposed when mouse hovers over a movie\show 

### ISSUE THREAD

**Issue by Stroked** [bbougot/Popcorn#29]
Presently, when user clicks on a movie, the whole movie gallery is hidden and only the summary with cast and HD selection is seen. 

I was thinking that if the summary was displayed at the bottom of the screen hovering over a darkered shadow area. Withthis I can scan way more movies by intro to storyline or description.

**Comment by bbougot** [comment]
This seems to be an interesting feature. However, I have prioritized other tasks and I don't know when I would be able to dev a draft of this one.

Feel free to submit a pull request if you want ;)
