### ISSUE TITLE
No Search function for TV Shows

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#30]
If users want to go directley for some TV show they want to see, they can't. User need to scroll down until he or she find the show he or she is looking for. (this could mean long time before finding the show) because TV Shows doesn't have Search function.

Movie section have search function along with a lot of others great things like Genre, sort out by defferent standards. I hope TV Shows would also get the same treatment in near future.

**Comment by bbougot** [comment]
As for now it is work in progress!

**Comment by Draxler** [comment]
ok. (it was just feature suggestion.)

**Comment by bbougot** [comment]
Fix in https://github.com/bbougot/Popcorn/commit/c30198e08a1dc5b1b973d7c3b0aa7af58945e2cf
