### ISSUE TITLE
Up/Download Rate Settings not working

### ISSUE THREAD

**Issue by HellGate94** [bbougot/Popcorn#32]
UI does not connect to the settings variables and also later on the usage of up and download speed is swapped

**Comment by HellGate94** [comment]
up and dowload are still sawpped in https://github.com/bbougot/Popcorn/blob/master/Popcorn/ViewModels/Pages/Home/Movie/Download/DownloadMovieViewModel.cs#L349

**Comment by bbougot** [comment]
Ok I will check this
