### ISSUE TITLE
Genre: Science Fiction doesn't work

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#34]
Win7/64Bit | 220Mbt/s |

When click on Science Fiction Genre nothing happened. It doesn't even try 2 search, it just open empty window right away with *No Movies Found* sign. 
It could be set on Popular , Greatest, Recent ; always the same result with Science Fiction genre.
(There are a lot of movies taged with Sci-Fi) 

![screenshot_5](https://cloud.githubusercontent.com/assets/7681671/25587667/52a5249a-2ea5-11e7-88ac-0ce26ae02beb.png)

**Comment by marvac** [comment]
Looks like this may have to do with "Science Fiction" and "TV Shows" having a space in the name

**Comment by Draxler** [comment]
After app update, this issue is still present. issue is not fixed.
And i'm talking about Movie section not TV section. (in my original post i'm talking about issue for  ''Movie section'' .) There is still empty page - no results for science fiction genre in movie section after update.
This issue should be reopened until it's fixed.

**Comment by marvac** [comment]
Looks like it was accidentally reverted when removing the french language logic. I'll submit a new PR for it soon

**Comment by marvac** [comment]
@bbougot may need to address this one. Your API requires a genre of "Sci-Fi" for movies and a genre of "Science-fiction" for TV shows.
I could write some logic to change the text based on movie/tv show query, but I don't think that's the best way to handle this

**Comment by bbougot** [comment]
I fixed this in https://github.com/bbougot/Popcorn/commit/9710f694f58bc085f845a31611ba72324edf05e6
