### ISSUE TITLE
I have created a SplashScreen gif for your consideration. 

### ISSUE THREAD

**Issue by UmarLone** [bbougot/Popcorn#43]
I fell in love with this software, its awesome. I watched three movies on it . I also shared with people.  If I can make some improvements in the code, how can I submit for review since I dont understand github so much.
![splashscreen](https://cloud.githubusercontent.com/assets/7713241/25685372/e91e62ac-3034-11e7-9ecc-37b3695778b8.gif)
please have a look. Thank YOU!

**Comment by bbougot** [comment]
Nice! The loader looks good :)
As regards improvement, feel free to submit a pull request ;)
