### ISSUE TITLE
Maximise hides taskbar

### ISSUE THREAD

**Issue by alimbada** [bbougot/Popcorn#46]
I can see the reason for this behaviour. Basically, there is not separate "fullscreen" feature for playing videos in fullscreen so the app hides the taskbar when it is "maximised" instead. However, this behaviour is inconsistent with other applications. Similar apps like VLC do not work like this. In order to provide a more consistent UX I think the behaviour should change to align with other video players.

I have some WPF experience and can submit a pull request if some direction is provided with regards to implementation. I can easily remove the taskbar hide behaviour by removing the `IgnoreTaskbarOnMaximize="True"` attribute in `MainWindow.xaml`.

**Comment by bbougot** [comment]
That makes sense! Fixed in https://github.com/bbougot/Popcorn/commit/9710f694f58bc085f845a31611ba72324edf05e6

**Comment by alimbada** [comment]
That was quick! Thanks! :)
