### ISSUE TITLE
Add option to choose another player like VLC

### ISSUE THREAD

**Issue by Pumpernikiell** [bbougot/Popcorn#49]

**Comment by bbougot** [comment]
This feature is complex, because the player must not block the file while being writen by libtorrent.
VLC is fine because it does not block I/O on file, but for example Windows Media Player does.
Maybe should we make a whitelist of players which are not blocking I/O?

**Comment by bbougot** [comment]
Moreover, subtitle support through the app is tightly coupled with VLC... I'm closing the issue.
