### ISSUE TITLE
Dark Theme = suggestion

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#51]
Is there a posibility to include (intergrate) also a dark theme for this Popcorn app? 
I have in mind to change colors only on few areas for second theme, so there be not to much trouble to do it and implementing it.
Now we have default light theme app version but we could also have a second dark theme for users to choose in the settings.

I have in mind something like this:

Dark Theme : (movie titles are missing under movie posters)

![screenshot_3](https://cloud.githubusercontent.com/assets/7681671/25780575/d6e0ca74-3329-11e7-9315-36de9168a4ca.png)

Settings (Theme - Toggle system):

![screenshot_14](https://cloud.githubusercontent.com/assets/7681671/25821186/6725453c-3434-11e7-800d-a8c2ddba7186.png)

**Comment by bbougot** [comment]
Would be nice. I will try something
