### ISSUE TITLE
App freezes (if moved in some area)

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#55]
win7/64b | latest app version 2.0.1
____________________________________

App freezes if grabed on some are and moved. (Issue in both sections: Movies and TV Series)
Look at screesnshot >>

![screenshot_10](https://cloud.githubusercontent.com/assets/7681671/26130929/62aebc04-3a97-11e7-917a-cb78db68ad45.png)

**Comment by bbougot** [comment]
Fixed in 36e847d8594d7570b685c50987aa64e1f90bec3f
