### ISSUE TITLE
Chromecast problem

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#59]
Please, look this gif I made
https://gfycat.com/ScholarlyThoughtfulGangesdolphin

**Comment by bbougot** [comment]
Same issue with release 2.0.8?

**Comment by Acme908** [comment]
In 2.0.8:
http://i.imgur.com/65VstQp.png

**Comment by bbougot** [comment]
I will investigate this soon

**Comment by theseraphim** [comment]
Have you managed to solve this between V2.0.8 and current 2.4.5?

ill be at home in 2 hours ill try casting to my chromecast, if it fails ill attach visual studio debugger and work through the problem

**Comment by bbougot** [comment]
The issue is still there. There is a problem with SharpCaster package which leads to, randomly, timeout for opening socket connexions to the Chromecast. I don't have much time to investigate more, but I think this issue (https://github.com/Tapanila/SharpCaster/issues/106) is related to it.

**Comment by bbougot** [comment]
It should be better with v2.4.6 (e0bdb54)

**Comment by bbougot** [comment]
Fixed in d65c627fd47bd4208d451f3914f7a8080daa2d95
