### ISSUE TITLE
Show miss episodes

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#60]
Looking for bugs (sry, just trying help) I see many Shows miss episodes, and not last.
List:

Better Call Saul: 3x06
In Popcorn: 2x10

Arrow: 5x22
In Popcorn:  5x15

The Flash: 3x21
In Popcorn: 3x14

The Big Bang Theory: 10x24
In Porpcorn: 10x17

I believe all shows are like this

**Comment by bbougot** [comment]
Thank you for your report! There was indeed an issue with PopcornExport. Fixed in https://github.com/bbougot/PopcornExport/commit/7a2044ae1c79b82ad521e1fe6bcdab8fbf282619.
Should be solved as of now 👍
