### ISSUE TITLE
App doesn't show last row of Favorite (Movies & TV) with scroller all the way down

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#62]
Win7/64b | Latest app version 2.3.1

Issue in Favorite section (Movies & TV)  
Issue is present also in full screen.

Look at screenshot  (screenshot updated = Text):

![z33](https://cloud.githubusercontent.com/assets/7681671/26372751/2fefc674-3fff-11e7-8a0b-c476dc54f9a5.PNG)

**Comment by bbougot** [comment]
Well spotted! I will fix this soon

**Comment by bbougot** [comment]
Fixed along with release 2.3.2
