### ISSUE TITLE
Hotkeys Improved

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#63]
**In player**
F = Toggle Fullscreen (so many media players use F key default to toggle fullscreen)
SPACE BAR and "Click on screen" = Play/Pause (currently need to click on a single play / pause button)
G / H = subtitles sync (0.1s)
Shift + G/H = subtitles sync (1s)

**Movie/Shows List**
Ctrl+F / F3 = Jump to Search
I = Open About window
F1 = Open Help window

**Comment by bbougot** [comment]
Fix in release 2.3.4
