### ISSUE TITLE
Internet going down

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#64]
I try use Popcorn in my work, and here internet go down every time when I try watch something, look:
https://gfycat.com/FailingLawfulIndigowingedparrot
(cmd.exe executing "ping google.com -t")

I tried to disable firewall and antivirus, but don't work.
In my home, I believe it's work fine.

Home and Work in Windows 10 x64

**Comment by bbougot** [comment]
Is there any proxy behind your network? At work it often the case, which may slow down your bandwidth.

**Comment by Acme908** [comment]
I do not think so, because the Router connects directly to the computer

**Comment by bbougot** [comment]
Could you make a Speedtest?
