### ISSUE TITLE
Suggestion for option: F12 = app Console

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#65]
I would suggest to include (implemented) option for app Console, so users would have an option to open app Console when press key F12. (same as Popcorn Time app have for Console to open with F12) 
This way issues would be found much more faster and eazy, if user could produce their console with issues to dev if necessary.

**Comment by bbougot** [comment]
That would be great but it is not feasible. Actually, this is the main difference between Popcorn (this project) and Popcorn Time. The last one is built using Node Webkit, which is a NodeJS wrapper, hence Javascript console is available.
Popcorn at the opposite is a fully native Windows application, which does not offer the ability to inspect app lifecycle in realtime.

**Comment by Draxler** [comment]
OK , Didn't know that ..
