### ISSUE TITLE
Suggestion: Offer larger main Popcorn icon

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#66]
Suggestion: 

Is it posible to offer larger >> 256x256 (HQ = High Quality) << main Popcorn icon 
instead what we have now, icon size only >>64x64 (LQ) << which doesn't look good 
as folder icon.

![screenshot_1](https://cloud.githubusercontent.com/assets/7681671/26408556/69bc7cc2-409e-11e7-9e42-7458e10666c1.png)

**Comment by bbougot** [comment]
Yup, I will create a larger one

**Comment by Draxler** [comment]
Thanks , i really appreciated.
