### ISSUE TITLE
Idea: Shows layout

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#68]
Actually Show view is this:
![01](http://i.imgur.com/AZCQFSA.jpg)

* Sinopse have so many space in header, but don't need that.
* Episode list is small, and Season Selector so far away

I suggest u to change this:

![02](http://i.imgur.com/qTym9yW.jpg)

* Show sinopse header small (because text never is so long) and if necessary a scroll bar
* Episode list big (show more episodes, maybe change font size for small)
* Season Selector close to Episode list
* Episode description bigger (easy to see release date, sinopse, watch button, subtitles and resolution) for big description of episode

Just say
Cya

**Comment by bbougot** [comment]
I will fix this
