### ISSUE TITLE
Unlicensed use of my source code

### ISSUE THREAD

**Issue by vktr** [bbougot/Popcorn#7]
Hello!

I've noticed that you have copied source code that belongs to me, from a repository with no license. A lack of license doesn't mean it's free for all, but rather the opposite.

The original repository with my code is here, https://github.com/vktr/libtorrent-net.
The copied sources (with no attribution, and a rather bold claim that they are **self made**) are here, https://github.com/bbougot/torrent.NET.
I filed an issue here, https://github.com/bbougot/torrent.NET/issues/1.

![image](https://cloud.githubusercontent.com/assets/1491824/23772693/3b749902-051c-11e7-898e-879d980d2230.png)

If you had asked I would have no problem adding a permissive license.

What is the purpose of copying my sources and promoting them as "self made"?

**Comment by bbougot** [comment]
Continuing conversation on bbougot/torrent.NET#1
