### ISSUE TITLE
Old commits and releases

### ISSUE THREAD

**Issue by alimbada** [bbougot/Popcorn#70]
Where did all the older commits and releases go?

**Comment by bbougot** [comment]
I have cleaned the repo to remove old and heavy git blobs (especially .nupkg files). Starting from now, all commits and releases will remain intact

**Comment by alimbada** [comment]
That's a shame. I'd like to see the changelogs from the previous releases at least. The latest version I have installed is 1.9.24 (which is currently not starting) and I can only see what's new from version 2.3.4.
