### ISSUE TITLE
Quality of subtitles

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#73]
Hi, is possible change subtitle quality for better? Look

Current:
![1](http://i.imgur.com/lFAosAS.jpg)

Other Popcorn:
![2](http://i.imgur.com/dC8a79C.jpg)

**Comment by bbougot** [comment]
I won't fix it any time soon (less time to dedicate to the project), but I will in the future

**Comment by CoderOffka** [comment]
Popcorn v2.6.6
Very good quality of subtitles

**Comment by Acme908** [comment]
Not for me @CoderOffka 
Btw, subtitles options don't work for me, I choose "Smaller" in options, but stay normal size in player, and color never change, aways white
![1](http://i.imgur.com/gUCU9Sa.png)
![2](http://i.imgur.com/tGJ2wb5.png)

**Comment by bbougot** [comment]
The color and size issue have been fixed along the latest release

**Comment by Acme908** [comment]
Pacially yes, in 2.7.1 if u change color first time, ok, but if u change one more time don't work, need closing software and re-open to change.
And quality is poor yet.

**Comment by bbougot** [comment]
Fixed in 3.3.0
