### ISSUE TITLE
Can't hide Download/Upload speed over video

### ISSUE THREAD

**Issue by TheManlyWay** [bbougot/Popcorn#77]
IT show in the top right corner of the ideo that is playing and can't be disabled or hidden, so it's kinda distracting, not a bug, but a minor distraction, so no rush with this.

**Comment by bbougot** [comment]
The download/upload tooltip should disappear after 5 seconds of user inactivity (as well as title and seekbar). Are you sure the mouse and keyboard are idle?

**Comment by TheManlyWay** [comment]
Maybe the touchpad is playing tricks on me... I'm gonna recheck this.

**Comment by TheManlyWay** [comment]
Yup, i need to clean it more often... sorry
