### ISSUE TITLE
Latest app ver. = in app ABOUT, latest app version have wrong TAG

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#79]
|| Win7/64B  |  Latest app version v2.4.10 ||
||-- --  --  --  --  --  --  - -  --  --  --  --  --  -- --||

Latest TAG in app About is TAGed as v2.4.9 (which is wrong).
--  --  --  --  --  --  --  --  --  --  --  --  --  --  -- --  --  --  
Latest TAG in about should be TAGed as v2.4.10 same as Github latest version.

______________________________________________________________________________________________

![screenshot_15](https://user-images.githubusercontent.com/7681671/28885679-02292f9c-77b7-11e7-9cce-a97f725b7b51.png)

![screenshot_14](https://user-images.githubusercontent.com/7681671/28885651-ef8b8a56-77b6-11e7-96f3-90f2996fe72e.png)

**Comment by bbougot** [comment]
You're right. Fixed in 9d46b6acb622ea5c7e5ce4f01ea3165c210283c7
