### ISSUE TITLE
Github latest version - download - instead .exe getting cross-site-scripting = warning by NoScript

### ISSUE THREAD

**Issue by Draxler** [bbougot/Popcorn#80]
|| Win7/64B  |  Latest app version v2.4.10 ||
||-- --  --  --  --  --  --  - -  --  --  --  --  --  -- --||

Github latest version, when try to download, instead of getting .exe file to download, 
new page gets open and get warning by NoScript about cross-site-scripting ...
(when NoScript is disabled i could download without any problem)
Issue is, if this is false positive or not, considering NoScript never did that before with non of your app version before when try to download .exe file from Github.
 _______________________________________________________________________________________________________

![screenshot_17](https://user-images.githubusercontent.com/7681671/28887049-fcc053fa-77bb-11e7-9829-06c54cd78301.png)

UPDATE: All your previous .exe releases also got this issue now. But with other apps .exe downloads on Github there is no issues.. (something has change, since your previous .exe versions didn't have this issue before when downloaded but now these same .exe files have this issue now when try to download)

**Comment by bbougot** [comment]
I confirm the issue but I can't do anything for this...
