### ISSUE TITLE
Russian subtitles are displaying in a wrong encoding

### ISSUE THREAD

**Issue by justbearcause** [bbougot/Popcorn#81]
When I select Russian subtitles they are displaying using a wrong encoding

E.g.:
![image](https://user-images.githubusercontent.com/12378791/29001823-0e65408c-7ab6-11e7-924d-54a35d9fd0ad.png)

**Comment by bbougot** [comment]
THe issue comes from the subtitles itself from Open Subtitles Database provider. From Popcorn app I can't do much to fix it
