### ISSUE TITLE
Unexpected show searching behavior

### ISSUE THREAD

**Issue by v3Monsta** [bbougot/Popcorn#82]
Searching for a movie that contains '&' displays just fine, however the same can't be said for show searching.

Version: 2.4.10

![Movie Search](http://i.imgur.com/dUf55a9.png)
![Show Search](http://i.imgur.com/YR4oGOe.png)

**Comment by bbougot** [comment]
Fixed in 0be2eefbef81ae1a0129826308277f28bb018c1a
