### ISSUE TITLE
Subtitles options

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#85]
Is possible change subtitles options in real time? Inside player? (size and color)
So boring need close the movie, go to settings, change options, back to player, see need more change and repeat.

**Comment by bbougot** [comment]
I will dig into soon

**Comment by reprec** [comment]
Also it would be great to have sync controls, as most of the times shows subtitles are off.

**Comment by Acme908** [comment]
@reprec but have it
G and H (shift+g, shift+h)
Press F1 in software to open HELP window with all keys

**Comment by reprec** [comment]
Thanks! Didn't know about that.

**Comment by Weeeishy** [comment]
Looking forward to this. Even though I have set my default subtitle language as Arabic in the settings. Yet, I have to manual switch it to Arabic every time, and I need to reload the movie/show.
