### ISSUE TITLE
Spanish APP translation

### ISSUE THREAD

**Issue by eilex** [bbougot/Popcorn#86]
Here you have an spanish translation patch of the app based on [d8d6bf9](https://github.com/bbougot/Popcorn/commit/d8d6bf901b4e64442e5be03de5d99b026d0873bb) commit.

[spansih translation - d8d6bf901b4e64442e5be03de5d99b026d0873bb.zip](https://github.com/bbougot/Popcorn/files/1229410/spansih.translation.-.d8d6bf901b4e64442e5be03de5d99b026d0873bb.zip)

**Comment by bbougot** [comment]
Awesome! I will apply the patch to the next version. Thank you so much!
