### ISSUE TITLE
ltnet.dll

### ISSUE THREAD

**Issue by CoderOffka** [bbougot/Popcorn#88]
could not load file or assembly ltnet.dll or one of its dependencies the specified module could not be found
Versions: 2.6.0 and 2.5.0
When I click on the watch button... The trailer button works well
![Image](https://pp.userapi.com/c836325/v836325859/5c60c/u-_St6gzAdU.jpg)

**Comment by bbougot** [comment]
In C:\Users\USER\AppData\Local\Popcorn\app-2.6.0:

* Do you have ltnet.dll, msvcp140.dll, vccorlib140.dll and vcruntime.dll ?
* If so, can you launch Dependency Walker (http://www.dependencywalker.com/, [download](http://www.dependencywalker.com/depends22_x86.zip) and extract it. Launch depends.exe then click on File -> Open and open ltnet.dll). Then File -> Save As (save your .dwi and send me the file)

**Comment by CoderOffka** [comment]
[File](https://vk.com/doc256356348_449650324?hash=4d1b05645f12c55838&dl=40247c8f9dabd10d12)
api-ms-win*.dll errors

**Comment by bbougot** [comment]
Should be fixed in v2.6.4 (vcomp140.dll dependency was missing).

**Comment by CoderOffka** [comment]
@bbougot it doesn't help :(

**Comment by CoderOffka** [comment]
api-ms-win-core-crt-l1-1-0.dll not found....

**Comment by bbougot** [comment]
Weird...
Which Windows do you have? The issue occurs while debugging with Visual Studio and launching the installed app?

**Comment by CoderOffka** [comment]
Windows 7 pro SP1...
With visual studio and the Popcorn.exe file when I click on the "watch" button.

**Comment by bbougot** [comment]
I will check with this OS. x86 or x64 ?

**Comment by CoderOffka** [comment]
x64

**Comment by CoderOffka** [comment]
@bbougot stop stop.... I'm debugging.... Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll

**Comment by bbougot** [comment]
I think I get it, I have targeted Win10 for ltnet build. UCRT is not fully available in Windows 7. I will fix it and deploy an update today.

**Comment by CoderOffka** [comment]
Yeeeah. Thank you so much!!
