### ISSUE TITLE
Stuttering video playback

### ISSUE THREAD

**Issue by theseraphim** [bbougot/Popcorn#90]
Hello, 

Ive noticed since the most recent update i moved to (2.6.1) that the video playback is not smooth, this is on both HD and SD videos.

Did anything change player wise? i'm investigating my driver situation as i know windows 10 likes to update without warning but i dont think anything significant changed on my end.

**Comment by bbougot** [comment]
Nothing has changed regarding video playback. The issue is there either for trailers or watching movies ?

**Comment by theseraphim** [comment]
Present in both movies and trailers, Windows 10 x64 enterprise.

**Comment by theseraphim** [comment]
I followed the file to the temp folder and pulled the exact file out and played in VLC just to make sure its not my computer having a fit, and it plays smooth, the playback is smoother when in less than fullscreen but still showing horizontal choppiness.

**Comment by theseraphim** [comment]
no... ignore this whole non-issue...

windows freaking 10 and its freaking "will update like it or not" ballsed something up, rollback and reboot fixed this issue.
