### ISSUE TITLE
In need of an installation wizard

### ISSUE THREAD

**Issue by popcornenthusiast** [bbougot/Popcorn#91]
A software for streaming of copyright protected content that silent installs itself and doesn't provide any info to the user during the installation process neither let him/her decides where it should be installed is kinda suspicious and definitely annoying. So, yes, Popcorn needs an installation wizard.

Some points on this:
- Make an installation wizard;
- Let the user decides where it should be installed, but do not allow installing it on more elevated directories (like Program Files) where Admin rights would be needed;
- Show the GNU GPL license in one of the installation steps;
- Show a "How does Popcorn works?" text in one of the steps with a short explanation on BitTorrent and torrenting of copyright protected content.

**Comment by bbougot** [comment]
That makes sense, I will dig into it later.

**Comment by beppe9000** [comment]
Remember also that many people prefer using programs that are self-contained in their own folder and carry them around different PCs (aka portable apps) so maybe support for installation on a USB drive could be added to the wizard.

**Comment by bbougot** [comment]
Actually, the installer is made for being stealth, without warning and so on (for those who would like to ask, it is Squirrel.Windows (https://github.com/Squirrel/Squirrel.Windows). I chose it to be fast with no prompt, so basically I will not be able to show an option to change the installation path.
