### ISSUE TITLE
Some TV Shows don't have all episodes

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#92]
Another:
https://i.imgur.com/BHPQZSO.png

This:
https://i.imgur.com/p56NLBi.png

Another:
https://i.imgur.com/G6RJ8sr.png

This:
https://i.imgur.com/edbLM53.png

Another:
https://i.imgur.com/3xSoRnb.png

This:
https://i.imgur.com/9PXoFYk.png

**Comment by bbougot** [comment]
Fixed with https://github.com/bbougot/PopcornExport/commit/b623890bcadf53065c4b74608c7680dfad0acab7

The batch which retrieves new movies and shows did not flush the Redis cache, so new episodes took some time to appear. Shoud be fine now
