### ISSUE TITLE
Chromecast working for anyone?

### ISSUE THREAD

**Issue by Acme908** [bbougot/Popcorn#99]
In my house never works.
In Popcorn show message it's ok, is possible pause and change options, but TV screen stay all black with a blue cast icon on center

This a internet photo, but is exact it in my house
![](https://lh3.googleusercontent.com/-PzzikrRw64o/V7InK-NPUoI/AAAAAAAAA18/Wdbzs-PT7CY_7I4FtOcS3JIWRklvTBRJQCLcB/s1600/20160815_151829.jpg)

**Comment by bbougot** [comment]
I will dig into it, but I'm aware of some Chromecast issues

**Comment by beppe9000** [comment]
maybe they have already fixed the issue? https://github.com/Tapanila/SharpCaster

**Comment by bbougot** [comment]
I am regulary watching the repo but the interesting feature and fix regarding this issue is handled by the PR https://github.com/Tapanila/SharpCaster/pull/119
I'm waiting for @Tapanila to close and merge it to the next release of SharpCaster

**Comment by kakone** [comment]
Did you try with my GoogleCast project ? https://github.com/kakone/GoogleCast

**Comment by bbougot** [comment]
@kakone Didn't know it exists! Thanks I will try to integrate it

**Comment by Tovarichtch** [comment]
The problem still persist. I have Chromecast 2 and Popcorn 3.3.2.
